CREATE DATABASE if not exists projectdb;
USE projectdb;
CREATE USER if not exists project_user@localhost;

GRANT ALL PRIVILEGES ON projectdb.* TO 'project_user'@localhost;
DROP TABLE IF EXISTS Courses;
CREATE TABLE Courses (CourseID INT PRIMARY KEY,Coursename VARCHAR(55), Semester_Offered INT);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1000, 'Game Design',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1011, 'African American Literature',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1022, 'Conflict Resolution',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1033, 'Color Theory',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1044, 'Introductory Microeconomics',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1055, 'Advanced Econometrics',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1066, 'Counseling Psychology',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1077, 'Conflict Resolution',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1088, 'Biological Anthropology',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1099, 'Creative Nonfiction Writing',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1110, 'American Sign Language',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1121, 'English Composition',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1132, 'Calculus I',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1143, 'Drama and Theater Arts',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1154, 'Database Design',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1165, 'Geology',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1176, 'Engineering Ethics',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1187, 'Biological Anthropology',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1198, 'American Sign Language',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1209, 'Elementary Spanish',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1220, 'Forensic Psychology',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1231, 'Cellular Biology',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1242, 'Geology',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1253, 'Biological Anthropology',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1264, 'Biological Anthropology',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1275, 'Computer Architecture',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1286, 'History of Ancient Rome',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1297, 'Contemporary Fiction',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1308, 'Game Design',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1319, 'Gender and Society',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1330, 'American Sign Language',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1341, 'Data Analysis and Visualization',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1352, 'Cognitive Psychology',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1363, 'Classical Mythology',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1374, 'Financial Management',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1385, 'Discrete Mathematics',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1396, 'East Asian History',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1407, 'Advanced Creative Writing',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1418, 'Business Ethics',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1429, 'Counseling Psychology',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1440, 'Calculus II',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1451, 'Information Systems',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1462, 'Computer Networks',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1473, 'Drama and Theater Arts',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1484, 'Cultural Anthropology',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1495, 'Cinematography',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1506, 'History of the American West',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1517, 'Chemical Kinetics',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1528, 'Developmental Psychology',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1539, 'Biological Anthropology',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1550, 'History of World Art',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1561, 'History of Ancient Rome',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1572, 'Drama and Theater Arts',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1583, 'Early Childhood Education',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1594, 'Feminist Philosophy',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1605, 'Biochemistry',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1616, 'Family Law',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1627, 'African American Literature',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1638, 'Economic Geography',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1649, 'Greek and Roman Civilization',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1660, 'Introductory Microeconomics',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1671, 'Epidemiology',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1682, 'Communication Ethics',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1693, 'Cognitive Psychology',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1704, 'Database Design',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1715, 'Anthropology of Religion',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1726, 'Information Systems',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1737, 'Creative Nonfiction Writing',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1748, 'Child Development',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1759, 'Computer Networks',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1770, 'Developmental Psychology',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1781, 'Film History',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1792, 'Advanced Creative Writing',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1803, 'Advanced Creative Writing',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1814, 'Evolutionary Biology',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1825, 'Geography of the Middle East',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1836, 'Greek and Roman Civilization',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1847, 'Classical Mythology',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1858, 'Food and Culture',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1869, 'Greek and Roman Civilization',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1880, 'College Algebra',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1891, 'Data Analysis and Visualization',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1902, 'Computer Programming',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1913, 'History of the American West',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1924, 'Anatomy and Physiology',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1935, 'African History',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1946, 'Civil War and Reconstruction',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1957, 'Information Technology and Society',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1968, 'History of Ancient Greece',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1979, 'Contemporary Fiction',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(1990, 'Digital Art and Design',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2001, 'History of the Middle East',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2012, 'History of American Architecture',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2023, 'Elementary Spanish',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2034, 'History of Ancient Rome',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2045, 'Chemical Engineering',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2056, 'Geology',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2067, 'Computer Architecture',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2078, 'Animal Behavior',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2089, 'Information Systems',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2100, 'Industrial and Organizational Psychology',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2111, 'Information Systems',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2122, 'Anthropology of Religion',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2133, 'History of American Architecture',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2144, 'Computer Security',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2155, 'Economics of Health',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2166, 'Evolutionary Biology',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2177, 'Conflict Resolution',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2188, 'History of American Architecture',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2199, 'Cultural Anthropology',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2210, 'Geography of Africa',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2221, 'Business Ethics',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2232, 'Comparative Literature',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2243, 'Computer Programming',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2254, 'Calculus II',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2265, 'Counseling Psychology',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2276, 'Drama and Theater Arts',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2287, 'Econometrics',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2298, 'Anthropology of Religion',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2309, 'History of American Architecture',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2320, 'Computer Security',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2331, 'Applied Statistics',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2342, 'Engineering Ethics',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2353, 'Financial Accounting',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2364, 'Computer Security',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2375, 'Business Ethics',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2386, 'History of Modern Europe',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2397, 'American Government',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2408, 'Financial Management',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2419, 'Human Resource Management',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2430, 'Discrete Mathematics',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2441, 'Classical Mythology',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2452, 'Computer Security',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2463, 'African History',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2474, 'Database Design',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2485, 'History of the Middle East',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2496, 'Computer Security',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2507, 'Globalization and Culture',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2518, 'Environmental Science',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2529, 'Corporate Finance',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2540, 'Greek and Roman Civilization',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2551, 'Elementary Spanish',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2562, 'Anatomy and Physiology',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2573, 'Biochemistry',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2584, 'African American Literature',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2595, 'Contemporary Issues in Education',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2606, 'Chemical Kinetics',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2617, 'International Relations',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2628, 'History of the American West',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2639, 'French Language and Culture',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2650, 'Game Design',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2661, 'Database Design',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2672, 'Geology',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2683, 'Drama and Theater Arts',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2694, 'Animal Behavior',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2705, 'Developmental Psychology',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2716, 'Game Design',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2727, 'Film History',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2738, 'Chinese Language and Culture',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2749, 'Geography of Africa',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2760, 'Experimental Psychology',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2771, 'Communication Ethics',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2782, 'Computer Organization',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2793, 'Geography of the Middle East',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2804, 'Anthropology of Religion',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2815, 'Earth Science',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2826, 'Classical Mythology',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2837, 'History of American Architecture',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2848, 'Chinese Language and Culture',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2859, 'Financial Accounting',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2870, 'International Relations',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2881, 'Family Law',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2892, 'Cellular Biology',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2903, 'Human Resource Management',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2914, 'Color Theory',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2925, 'Abnormal Psychology',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2936, 'Cultural Anthropology',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2947, 'Computer Programming',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2958, 'Applied Statistics',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2969, 'Earth Science',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2980, 'Ancient Greek Civilization',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(2991, 'Counseling Psychology',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(3002, 'Digital Photography',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(3013, 'Cinematography',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(3024, 'Anthropology of Religion',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(3035, 'French Language and Culture',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(3046, 'Experimental Psychology',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(3057, 'British Literature',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(3068, 'Feminist Philosophy',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(3079, 'Business Ethics',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(3090, 'Contemporary Art',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(3101, 'Comparative Literature',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(3112, 'Contemporary Art',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(3123, 'International Business',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(3134, 'American Literature',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(3145, 'Introductory Microeconomics',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(3156, 'Calculus II',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(3167, 'Computer Security',2);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(3178, 'German Language and Culture',1);
INSERT INTO Courses (CourseID,Coursename,Semester_Offered ) VALUES(3189, 'History of the American West',1);

select * from courses;
INSERT INTO Courses(CourseID,Coursename,Semester_Offered ) VALUES(3180, 'Web Development', 2);

SELECT * FROM Courses WHERE CourseID = '3180' AND Coursename = 'Web Development';

SELECT Coursename FROM Courses WHERE CourseID = 3180;